## **Reshaping**

In [1]:
import numpy as np

In [2]:
arr_angles = np.array([0 , 45 , 90, 180])
print('Angles = ', arr_angles)

ar_cos = np.cos(arr_angles)
print('\nCos of the angles are : ', ar_cos)

ar_sin = np.sin(arr_angles)
print('\nSin of the angles are :', ar_sin)

ar_tan = np.tan(arr_angles)
print('\nTan of the angles are :', ar_tan)

ang_to_rad = np.deg2rad(arr_angles)
print('\nConverting Angles into Radians :', ang_to_rad)

Angles =  [  0  45  90 180]

Cos of the angles are :  [ 1.          0.52532199 -0.44807362 -0.59846007]

Sin of the angles are : [ 0.          0.85090352  0.89399666 -0.80115264]

Tan of the angles are : [ 0.          1.61977519 -1.99520041  1.33869021]

Converting Angles into Radians : [0.         0.78539816 1.57079633 3.14159265]


In [3]:
import numpy as np

# Create an array of angles (in degrees)
angles = np.array([0, 30, 45, 60, 90])

# Convert degrees to radians
angles_rad = np.radians(angles)

# Calculate sin, cos, and tan
sin_values = np.sin(angles_rad)
cos_values = np.cos(angles_rad)
tan_values = np.tan(angles_rad)

print("Sine values:", sin_values)
print("Cosine values:", cos_values)
print("Tangent values:", tan_values)

Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [4]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [5]:
# reshape

`.T` and `np.transpose`

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Transpose
np.transpose(a1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [12]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

`Ravel` is a method of numpy which will convert any shape or dimension of array into `1D` array

In [13]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
# ravel
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## **Stacking**

In [16]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [17]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

`Tuple argument`

In [19]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# horizontal stacking
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [22]:
# Vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## **Splitting**

`hsplit` and `vsplit`

In [23]:
# horizontal splitting

In [24]:
# vertical splitting

## **Numpy array vs Python lists**

In [25]:
import time
# speed
# list

l1 = [x for x in range(10000000)]
l2 = [x for x in range(10000000, 20000000)]

start = time.time()

l3 = []
for x in range(10000000):
    l3.append(l1[x] + l2[x])

stop = time.time()
print(stop - start)

3.2110519409179688


In [26]:
# numpy
n1 = np.arange(10000000)
n2 = np.arange(10000000, 20000000)
start = time.time()
n3 = n1 + n2
print(time.time() - start)

0.030075550079345703


In [27]:
0.283766508102417/0.00800633430480957

35.44275036478961