## **Advanced Indexing**

In [32]:
import numpy as np 

In [33]:
a = np.arange(24).reshape(6,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
# Normal Indexing and slicing
a[2, 1:3]

array([ 9, 10])

### Fancy Indexing

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
a[2, 2]

np.int64(10)

In [38]:
a[[4, 2], [1, 2]]

array([17, 10])

### Boolean Indexing

In [67]:
a1 = np.random.randint(1, 100, 24).reshape(6,4)

In [68]:
a1

array([[38, 52, 11, 46],
       [96, 13, 16, 63],
       [27, 40, 87, 60],
       [40, 47, 15, 88],
       [ 4, 84, 74, 65],
       [58, 83, 92, 73]], dtype=int32)

Boolean array is also known as boolean mask

In [41]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [42]:
# find all numbers greater than 50
a1[a1 > 50]

array([57, 61, 61, 83, 99, 91], dtype=int32)

In [43]:
a1

array([[32,  5, 30, 57],
       [ 9, 61, 19, 28],
       [61, 30,  3, 16],
       [83, 23, 25, 36],
       [99,  9, 33,  5],
       [ 1, 91, 50,  8]], dtype=int32)

In [44]:
# find out even numbers
a1[a1 %2 == 0]

array([32, 30, 28, 30, 16, 36, 50,  8], dtype=int32)

Use `Bitwise` `Operators`

working with booleans

In [45]:
# find all numbers greater than 50 and are even
a1[(a1 > 50) & (a1 % 2 == 0)]

array([], dtype=int32)

In [46]:
a1[(a1 > 50) & a1 %2==0]

array([32,  5, 30,  9, 19, 28, 30,  3, 16, 23, 25, 36,  9, 33,  5,  1, 50,
        8], dtype=int32)

In [47]:
# find all numbers not divisible by 7
a1[a1 % 7 != 0]

array([32,  5, 30, 57,  9, 61, 19, 61, 30,  3, 16, 83, 23, 25, 36, 99,  9,
       33,  5,  1, 50,  8], dtype=int32)

## **Broadcasting**

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [48]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
sum = a + b
print(sum)

[[ 6  8 10]
 [12 14 16]]


In [51]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

In [52]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
b

array([[0, 1, 2]])

In [54]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])

## **Broadcasting Rules**

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

### **Examples**

In [55]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

In [56]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
b

array([0, 1, 2])

In [58]:
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

`(1, 3)`

`(3, 4)`

In [59]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

In [60]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
b

array([0, 1, 2])

In [69]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

In [ ]:
a

array([[0, 1, 2]])

In [ ]:
b

array([[0],
       [1],
       [2]])

In [ ]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

a

array([1])

In [ ]:
b

array([[0, 1],
       [2, 3]])

In [ ]:
a + b

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 