# Indexing and Slicing

### **Indexing**

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a1[3]

np.int64(3)

In [5]:
a1[0:4] # Start : Stop : Step

array([0, 1, 2, 3])

In 2D Array we use indexing like this

`[row,column]`

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a2[2, 1]

np.int64(9)

In [8]:
a2[0:2, 0:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [9]:
a2[2, 3]

np.int64(11)

In [10]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a2[1, 0]

np.int64(4)

In 3D array we get th items using this method.
WE know that all 3D array are made from 2D Arrays.
So in this method we have to understand which 2D Array we are talking about.

`array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])`
        
Lets consider we want to fetch the `3` from the above.

First we have to which 2D array it is in, then which row and whoch column

`[0,1,1]`

In [12]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# [rows, columns]
# [2D, rows, columns]

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3[0:3, 0 : 4, 1:3]

array([[[1],
        [3]],

       [[5],
        [7]]])

In [16]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a3[1, 1, 0]

np.int64(6)

In [18]:
a3 = np.arange(27).reshape(3, 3, 3)

In [19]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
a3[1, 1, 1]

np.int64(13)

In [21]:
a3[2, 1, 1]

np.int64(22)

### **Slicing**

So Slicing the 2D array we have to specify which row we want to slice and after that we have to tell which columns we want to slice.

In [22]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1[4:8] # [include:exclude]

array([4, 5, 6, 7])

In [24]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`[rows, columns]`

In [25]:
a2[0, 2:]

array([2, 3])

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2[1, 1:3]

array([5, 6])

In [28]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a2[0, 1::2]

array([1, 3])

In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`[row:column]`

In [31]:
a2[2, 1::2] # 1

array([ 9, 11])

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2[1, 2:]

array([6, 7])

In [34]:
a2[2, 0::3]

array([ 8, 11])

In [35]:
import numpy as np

In [36]:
a = np.arange(27).reshape(3, 9)

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [38]:
a[1, 0::7]

array([ 9, 16])

In the case of 3D Array we do the same thing as we did in indexing

`[2Darray, row, column]`

In [39]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
a3[1, 2, 0::2]

array([15, 17])

In [41]:
a3[0::2, 1, 1]

array([ 4, 22])

In [42]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
a3[2, 1:, 0]

array([21, 24])

In [44]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[0:, 1, 0]

array([ 3, 12, 21])

# **Iterating**

In [46]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
## Loops
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [48]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:

for i in x:
     print(i)

8
9
10
11


In [ ]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


Concept of `np.nditer`

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in np.nditer(a3):
    if i % 2 == 0 and i !=0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
