## **Attribute of Array**

In [1]:
import numpy as np

In [47]:
a1 = np.arange(10.)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [3]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
# ndim
a2.ndim

2

In [8]:
# shape
a2.shape

(3, 4)

In [9]:
a1.ndim

1

In [10]:
a3.shape

(2, 2, 2)

In [11]:
# size
a3.size

8

In [12]:
# itemsize
a2.itemsize

8

In [13]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
# dtype
print(a1.dtype)

float64


In [15]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
print(a2.dtype)
print(a3.dtype)

float64
int64


In [18]:
# astype
a1.astype(np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [19]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
a2.astype(np.int8)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int8)

## **Array Operations**

In [21]:
# scalar operations

# arithmetic
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(11,23).reshape(3,4)

In [22]:
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]))

In [23]:
a1 / a2

array([[0.        , 0.08333333, 0.15384615, 0.21428571],
       [0.26666667, 0.3125    , 0.35294118, 0.38888889],
       [0.42105263, 0.45      , 0.47619048, 0.5       ]])

In [24]:
# relational
a1 == a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [28]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                 8192,
                     4782969],
       [          1073741824,         152587890625,       16926659444736,
            1628413597910449],
       [  144115188075855872, -6289078614652622815,  3875820019684212736,
        -2732210440490168087]])

## **Array Functions**

In [29]:
a1 = np.random.random((3,3))

In [30]:
a1

array([[0.99043651, 0.09520287, 0.51590323],
       [0.76288785, 0.86646795, 0.65741324],
       [0.98475117, 0.61723752, 0.71990691]])

In [31]:
round(0.63543655 * 100, 2)

63.54

In [32]:
a1 = np.round(a1*100)

In [33]:
a1

array([[99., 10., 52.],
       [76., 87., 66.],
       [98., 62., 72.]])

In [34]:
a1

array([[99., 10., 52.],
       [76., 87., 66.],
       [98., 62., 72.]])

In [35]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1, axis=0)

array([99., 87., 72.])