---
## **Numpy**
---

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the nd array object. This encapsulates n-dimensional arrays of homogeneous data types

NumPy was created in **2005** by **Travis Oliphant**. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

Back in 2000 - 2004 python is not consider to work as Library in Data Analysis and Data Science Domain. People use **R** and some other Programming Language for this Domain, because **python** is consider as a slow processing Programming Language. But when someone create this **numpy package** then the game changes and at that time **Python** is choosen as a Programming Language which will used in Data Science and AI Domains.

Numpy library is acctually created in **C** Programming Language.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

> **NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.**

### Here’s why NumPy is essential:

### Key Features of NumPy:

- N-dimensional array (ndarray):

The core feature of NumPy is the ndarray object, which is a multi-dimensional container for homogeneous data (i.e., all elements are of the same type, usually numbers).
It can handle arrays of any dimension (1D, 2D, 3D, etc.), making it highly versatile for numerical computations.
- Efficient memory usage:

NumPy arrays are more compact and faster than Python lists. This is because NumPy stores data in contiguous blocks of memory and performs operations element-wise using compiled C code, leading to significant speed improvements.
- Vectorized operations:

NumPy allows you to perform operations on entire arrays at once without the need for explicit loops. This concept is called "vectorization," and it leads to cleaner, more efficient, and faster code.
- Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes and sizes by automatically adjusting the smaller array so that it aligns with the larger one during operations.
- Mathematical functions:

NumPy provides a wide range of mathematical functions, including trigonometric functions, linear algebra, statistical operations, and random number generation.
- Integration with other libraries:

NumPy arrays are the backbone of many other scientific libraries like Pandas, Scikit-learn, and TensorFlow, making it crucial for data analysis, machine learning, and deep learning.

## **ARRAY**

In [1]:
import numpy as np

In [ ]:
# np.array
np.array([1, 2, 3, 4, 5, 5])

array([1, 2, 3, 4, 5, 5])

In [ ]:
type(np.array([1, 2, 3, 4, 5, 5]))

numpy.ndarray

In [ ]:
# 2D and 3D
np.array([[1, 2, 3, 4],
          [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a = np.array([[[1, 2, 3],
           [3, 2, 1],
           [9,8,7]],

           [[6, 4, 3],
            [4, 5, 6],
            [8,5,3]]])

In [ ]:
# dtype
a.dtype

dtype('int64')

In [ ]:
a1 = np.array([[1, 2, 4.],
               [3, 2, 1]])

a1.dtype

dtype('float64')

In [ ]:
# np.arange
np.arange(2., 11, 2)

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
# with reshape
np.arange(1., 26).reshape(5, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [ ]:
# np.ones and np.zeros
np.ones((2, 20))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [ ]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
# np.random
np.random.random((3,4))

array([[0.34647994, 0.24072466, 0.80414463, 0.05242172],
       [0.08775352, 0.69067482, 0.91626763, 0.92177847],
       [0.48906803, 0.42484816, 0.45725733, 0.0676109 ]])

In [ ]:
# np.linspace
# np.linspace
np.linspace(-10, 10, 20) ## (Lower range, Upper Range, Number of Items)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [4]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])